### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by CharlesARoy** [oluevaera/tmux-conda-inherit#1]
Hello,

I love the idea of this plugin but I can't seem to get it working. I followed the installation instructions to the letter but when I create a new window, the Conda environment reverts to base.

I did notice that even though I added the following line to my tmux config, the `TMUX_PARENT_PANE_ID` variable doesn't appear to be set (it the old window or the new one) when I run Prefix-c.

```
bind c run 'tmux new-window -c "#{pane_current_path}" -e "TMUX_PARENT_PANE_ID=#{pane_id}"'
```

That seems like the key part that the conda-inherit.sh script is missing to auto-activate the original environment. I also noticed that when I create a new window, I get an output that says:
```
original_conda: command not found
```

Any suggestions?

**Comment by CharlesARoy** [comment]
ChatGPT solved it for me 😅

Probably obvious to anyone who actually knows what they're doing, but the following code that needs to be added to your `.bashrc` or `.zshrc` file has to be located **_after_** the "conda initialize" code managed by conda (that sources the .../anaconda3/etc/profile.d/conda.sh script to define the conda function).

```
if [[ -n "$TMUX" ]] then
  export flavor='conda'
  source $HOME/.config/tmux/plugins/conda-inherit/conda-inherit.sh
fi
```

**Comment by oluevaera** [comment]
Hello, 

Thank you for taking the time to open an issue!  

I'm glad you were able to find a solution to your problem. Based on your feedback, I have now clarified in the README file that the mentioned code should be added **after** the conda initialize block.  

Thank you for using the plugin! 😊
